### ISSUE TITLE
Bard as starting job

### ISSUE THREAD

**Issue by Rom-Stein** [IgnacioCartes/ff3-randomizer#2]
When you include the Onion Knight in the randomized jobs, there is a chance that you get the Bard as your starting job, which means the first fight (4 bards vs the gobelins) is not winnable due to the bards not having the "Attack" command, and unable to sing (no harp equipped).
The randomizer needs a logic that tells him he can't put jobs without "Attack" command as a starting job if the player includes Onion Knight in the randomized job pool.

**Comment by nachoyacopu** [comment]
Thanks, I have addressed this and will update the patch as soon as possible.
