### ISSUE TITLE
Summoner/Sage gets the Call effects from the Conjurer job?

### ISSUE THREAD

**Issue by AcaliaDesu** [IgnacioCartes/ff3-randomizer#4]
Whenever a Summoner or a Sage cast a Call type spell, they still use the Conjurer effect of that Call spell, rather than the ultimate effect from the normal Summoner/Sage.

Example: 
Ifrit will use either "Recover" or "Flames of Fury", but never "Hellfire".
Bahamut will use either "Aura" or "Rend", but never "Mega Flare".

This happens even if you're a Summoner/Sage, basically making the Call magic kinda bad.

**Comment by nachoyacopu** [comment]
Thanks for the issue, I managed to find the relevant addresses and updated the randomizer so now Summoner/Sages should always cast the ultimate effect for all summons.
